name: auth
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  introduction_screen: ^3.1.17
  shared_preferences: ^2.5.2
  flutter_native_splash: ^2.4.4
  responsive_builder: ^0.7.1
  file_picker: ^9.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.2
  flutter_stripe: ^11.4.0
  flutter_paypal: ^0.2.1
  go_router: ^14.8.0
  webview_flutter: ^4.4.4
  flutter_paypal_payment: ^1.0.8
  http: ^1.3.0
  url_launcher: ^6.3.1
  timelines_plus: ^1.0.6

flutter_native_splash:
  color: "#FF6600" # Change this to any color (e.g., white)
  image: assets/images/logo.png # Add your splash logo (optional)
  fullscreen: true # Makes the splash screen cover the whole screen

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FF6600" # Background for Android 12+
    fullscreen: true




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/animations/one.json
    - assets/animations/turbine.json
    - assets/animations/two.json
    - assets/images/login.svg
    - assets/images/register.svg
    - assets/images/reset_pass.svg
    - assets/animations/knife.gif
    - assets/images/logo.png
    - assets/images/rr.png
    - assets/animations/no_data.json

  uses-material-design: true

